Create Navbar of Portfolio
codedbystuart/portfolio pull request #1
Opened 2022-08-17 20:11 UTC by codedbystuart

## Feature Instructions

### HTML & CSS Linting and Github Workflows
Completed setup for linting and Github workflows

### Changes Made
* css/styles.css
* index.html

2022-08-17 22:12 UTC, topeogunleye requested changes
Hi @codedbystuart, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your @topeogunleye so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 22:12 UTC, topeogunleye commented on index.html
> +  <div class="welcome-area">
- [ ] I kindly suggest that you add the proper background images to the headline section. Kindly check Figma design below:

| Your Design  | Figma Design |
| ------------- | ------------- |
|![image](https://user-images.githubusercontent.com/52934128/185250746-43f2fcf8-7655-4183-83f3-d4c60fa0c011.png)  | ![image](https://user-images.githubusercontent.com/52934128/185251352-e42fc24a-ec98-4753-8c54-bb87c539a443.png)  |

- [ ] I kindly suggest that you change the tag of your `welcome-area` from a `div` to a `section` tag because it is a project requirement and it helps with semantics

2022-08-17 22:12 UTC, topeogunleye commented on index.html
> +    <div class="social-links">
- [ ] I kindly suggest that you try to change this div tag to an `<ul>` tag and make the `<i>` for each one inside `<li>` tag, it will makes your HTML structure better and follows the right semantics.

2022-08-18 06:20 UTC, codedbystuart commented on index.html
> +    <div class="social-links">
@topeogunleye , this has been fixed

2022-08-18 06:20 UTC, codedbystuart commented on index.html
> +  <div class="welcome-area">
@topeogunleye , this has also been fixed

2022-08-18 08:56 UTC, ichala approved these changes
Hi @codedbystuart ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻
✅ You used the correct Github Flow.
✅ Professional README.
✅ No Linters errors.
✅ .gitignore looks great.


Good job implementing the required changes :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
*************************************
# Optional Suggestions 

- [ ] **_Check the comments bellow_**


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 08:56 UTC, ichala commented on index.html
> +      <li><a href="#" class="developer">Dambi Stuart</a></li>
- [ ] [OPTIONAL] your project looks super awesome and clean I'm really impressed 💯 kindly try to add the correct font family to the menu Logo, currently it has no font and in Figma its `Roboto`

2022-08-18 08:56 UTC, ichala commented on index.html
> +      <li><a href="#"><i class="fa-solid fa-bars 2x"></i></a></li>
- [ ] [OPTIONAL] _**this comment is optional but highly recommended**_ : 
For best semantics practices, kindly wrap your  hamburger  button with the `<nav>` tag,

2022-08-18 09:24 UTC, codedbystuart commented on index.html
> +      <li><a href="#"><i class="fa-solid fa-bars 2x"></i></a></li>
Thanks @ichala

2022-08-18 09:29 UTC, ichala commented on index.html
> +      <li><a href="#"><i class="fa-solid fa-bars 2x"></i></a></li>
@codedbystuart you are welcome, you did a great job! keep rocking 🥇

2022-08-18 10:05 UTC, merged