Connect Formspree to contact form
codedbystuart/portfolio pull request #3
Opened 2022-08-23 13:48 UTC by codedbystuart

## Changes
* index.html

## Features
Added functionality to contact form using formspree

2022-08-23 14:13 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @codedbystuart, and @Maxwell011👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 14:13 UTC, thecodechaser commented on index.html
> +      <form action="https://formspree.io/f/xnqrnjll" method="post">
- [ ] Please use the correct font weight for the heading and make sure it matches the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471) design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/186180034-b721d2d4-35e4-4161-8ae0-69866315a2da.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/186179967-6e3a0e0f-e665-4244-b9f1-0b9b7c72e59f.png)

2022-08-23 14:13 UTC, thecodechaser commented on index.html
> +        <input type="submit" class="submit form-item" value="Get in Touch" />
- [ ] Please implement the button interaction for this submit button. (Hover, Active, etc.)
![image](https://user-images.githubusercontent.com/83803414/186180941-f2254c7b-c90e-45ac-b2d3-74d36957306e.png)

2022-08-24 16:04 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @codedbystuart & @Maxwell011 ✋

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" width="480" height="270" class="giphy-embed" />

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-25 05:28 UTC, merged